// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2u6oLXutLCCVsyIpMpqJI0ZMF8Mpqyn0',
    appId: '1:754534998239:web:843a0b42c9e9ae19d1096a',
    messagingSenderId: '754534998239',
    projectId: 'internationalcuisine-31b41',
    authDomain: 'internationalcuisine-31b41.firebaseapp.com',
    databaseURL: 'https://internationalcuisine-31b41-default-rtdb.firebaseio.com',
    storageBucket: 'internationalcuisine-31b41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdGFVb-vIQc1WIMgZyh9_Yc301hkYYj8',
    appId: '1:754534998239:android:d1c1490fb9fbd81ad1096a',
    messagingSenderId: '754534998239',
    projectId: 'internationalcuisine-31b41',
    databaseURL: 'https://internationalcuisine-31b41-default-rtdb.firebaseio.com',
    storageBucket: 'internationalcuisine-31b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOZ9C_JuOhz6fVeCtZ3XYUuuxIWuE-nQ',
    appId: '1:754534998239:ios:23c047d63e0336d4d1096a',
    messagingSenderId: '754534998239',
    projectId: 'internationalcuisine-31b41',
    databaseURL: 'https://internationalcuisine-31b41-default-rtdb.firebaseio.com',
    storageBucket: 'internationalcuisine-31b41.appspot.com',
    iosBundleId: 'com.example.internationalCuisine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZOZ9C_JuOhz6fVeCtZ3XYUuuxIWuE-nQ',
    appId: '1:754534998239:ios:23c047d63e0336d4d1096a',
    messagingSenderId: '754534998239',
    projectId: 'internationalcuisine-31b41',
    databaseURL: 'https://internationalcuisine-31b41-default-rtdb.firebaseio.com',
    storageBucket: 'internationalcuisine-31b41.appspot.com',
    iosBundleId: 'com.example.internationalCuisine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2u6oLXutLCCVsyIpMpqJI0ZMF8Mpqyn0',
    appId: '1:754534998239:web:1e7c855a0b2729f4d1096a',
    messagingSenderId: '754534998239',
    projectId: 'internationalcuisine-31b41',
    authDomain: 'internationalcuisine-31b41.firebaseapp.com',
    databaseURL: 'https://internationalcuisine-31b41-default-rtdb.firebaseio.com',
    storageBucket: 'internationalcuisine-31b41.appspot.com',
  );
}
